# Generated by Django 3.1.7 on 2021-04-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210224_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userauth',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
